### PR TITLE
Make all default workflow commands start with .bw

### PR DESCRIPTION
**Pull request by GabLeRoux**
By looking at the docs, at some places in the docs, it was mentioning `.bwauth` and `.bitauth`. 

The one that confused me was `.bwauto` which wasn't available and looking in the config, I saw it was `.bitauto` instead. 

To make it easier for new users, I made everything start with `.bw` and got rid of everything starting with `.bit` in the defaults.

This stays a user configuration so people updating might want to set them back to what they preferred using, but at least, documentation and configuration will now match.

Oh and this workflow is really useful, thank you so much!

_Note: I did not try building this, I did these changes by hand in my own configuration, forked and use search and my head so you might want to double check things if you want to merge this 👍_

### CODE REVIEW

**Comment by GabLeRoux** [comment]
_Note 2: for reference, I did open a pr at the wrong destination (initial upstream repo) and closed it to target here instead. :)_
https://github.com/stuartcryan/lastpass-alfred-workflow/pull/69

**Comment by blacs30** [comment]
Thanks for this PR. The change away from starting `.bw` for every command was done on purpose.
The reason behind the change is that it was difficult to get to the other options before successful login (`.bwconf` contains `.bw` - some checks happen as soon as `.bw` is typed)

One option I could image would work is to rename the default `.bw` to `.bws`

What do you think about that?

**Comment by GabLeRoux** [comment]
I would prefer to configure using .bitwarden and use .bw for everything else as we only configure once

**Comment by claas-fridtjof-lisowski** [comment]
Okay, that's fine with me.

**Comment by blacs30** [comment]
Okay, that's fine with me.

**Comment by blacs30** [comment]
I've added the changes as requested in my own PR https://github.com/blacs30/bitwarden-alfred-workflow/pull/116
additionally I removed the auto start of the sync (an item which allows to trigger the sync is added now instead) -
so that we can have all items back under `.bw` without any trouble.

**Comment by blacs30** [comment]
Closing because the changes are included in [release 2.4.1](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.4.1)

**Pull request closed without merging**
