### PR TITLE
add 2 troubleshooting topics

### LINKED ISSUE #60: link scripts in readme
Hey @blacs30 👋 

I played around with the auth tokens and figured out a way to make them play nice with each other. I only tested it minimally but I think this could be useful... see → [luckman212/bitwarden-cli-helpers](https://github.com/luckman212/bitwarden-cli-helpers)

With these helper functions in `.bash_profile` (or `.zshrc` if that's your thing) you can pass auth tokens back and forth between your Workflow and the `bw` CLI without invalidating the other session key.

Let me know what you think. Hopefully we can close up this issue and #49 if everything's happy. Things have been working pretty well for me using 2.2.1-test5.

_Originally posted by @luckman212 in https://github.com/blacs30/bitwarden-alfred-workflow/issues/53#issuecomment-730794727_

### PR DESCRIPTION
**Pull request by blacs30**
fixes #60

### CODE REVIEW

**Comment by blacs30** [comment]
Hi @luckman212,
since you are so active here, may I ask you, if you find time, to review this update. 
I'm no native english speaker so some things might sound strange to a native, which would be great to clean up.
🙏

**Comment by luckman212** [comment]
Sure thing, I'm working on the PR now, and I'll read through as much as I can and try to spot anything else. 👍

**Comment by blacs30** [comment]
@luckman212 Happy new year.
I understand you might be busy with other things. 
For now I will go ahead and merge this PR and if you want and find time at a later point I'd be thankful for a review of the README.

**Comment by luckman212** [comment]
@blacs30 yes, Happy new year! You're right- somehow the copious spare time I was enjoying just a couple of weeks ago has disappeared, and suddenly I find myself a bit busy.

It's after midnight here but I promise to dedicate some time tomorrow on this.

**Pull request merged**
