### PR TITLE
compiles a universal binary for amd64 and arm64

### PR DESCRIPTION
**Pull request by jcolson**
quick update to build a universal binary

### CODE REVIEW

**Comment by blacs30** [comment]
Good idea, thanks for this PR. Probably the release should use the Makefile, however at the moment it's compiling directly in the release step:
https://github.com/blacs30/bitwarden-alfred-workflow/blob/master/.github/workflows/release.yml#L38
May I ask you to update this also?

**Comment by jcolson** [comment]
> Good idea, thanks for this PR. Probably the release should use the Makefile, however at the moment it's compiling directly in the release step:
> https://github.com/blacs30/bitwarden-alfred-workflow/blob/master/.github/workflows/release.yml#L38
> May I ask you to update this also?

sure, i didn't look deep enough to realize you where using github workflows until after i submitted the PR ;-)  will  take a look

**Comment by blacs30** [comment]
Thank you for looking into this and testing it out.
`unless you want to write a custom setup for go installation.` - I think I don't. 

Golang 1.16 is expected to be released in February -> [https://tip.golang.org/doc/go1.16](https://tip.golang.org/doc/go1.16)
Is it okay to wait until then?

**Comment by jcolson** [comment]
No worries, I'll check back in in Feb.

**Comment by blacs30** [comment]
@jcolson Golang 1.16 is available [https://golang.org/doc/install](https://golang.org/doc/install) :)

**Pull request closed without merging**
